# Generated by Django 4.1.7 on 2023-05-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admn_no', models.IntegerField(default=0)),
                ('sname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('aadharno', models.IntegerField(default=0)),
                ('email_id', models.EmailField(max_length=254)),
                ('phno', models.IntegerField(default=0)),
                ('address', models.TextField()),
                ('course', models.CharField(max_length=100)),
                ('doj', models.DateField()),
                ('duration', models.PositiveIntegerField(default=0)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('recorded', 'Recorded')], max_length=10)),
                ('course_fee', models.IntegerField(default=0)),
                ('emi', models.IntegerField(default=0)),
            ],
        ),
    ]
