# Generated by Django 4.1.7 on 2023-05-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registers',
            name='permonth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
